#pragma once
enum AST_Kind {
  // Compounds
  AST_NULL_NODE = 0,

  AST_UNDEFINED_NODE,
  AST_UNITIALIZED_NODE,

  __AST_KIND_BEGIN,

  AST_PROGRAM_POINT,

  AST_CALL_ARGS_LIST,
  AST_DECL_ARGS_LIST,

  AST_WITH_HANDLER,

  // Control Flow
  __AST_CTRL_FLOW_START,
  AST_CTRL_FLOW_IF,
  AST_CTRL_FLOW_IF_ELSE,
  AST_CTRL_FLOW_RETURN,
  AST_CTRL_FLOW_MATCH,
  AST_CTRL_FLOW_CASE,
  __AST_CTRL_FLOW_END,

  // Bindings
  AST_BIND_CONSTANT,
  AST_BIND_VARIABLE,
  AST_BIND_TYPE,

  // Declarations
  __AST_LITERAL_START,
  AST_SYMBOL_LITERAL,
  AST_NATURAL_LITERAL,
  AST_FUNCTION_LITERAL,
  AST_HANDLER_LITERAL,
  __AST_LITERAL_END,

  AST_FUN_SIGNATURE,

  // Types
  __AST_TYPE_KIND_START,
  AST_TYPE_I32,
  AST_TYPE_UNIT,
  AST_TYPE_ANY,
  AST_TYPE_ARROW,
  AST_TYPE_EFFECT,
  AST_TYPE_TUPLE,
  AST_TYPE_TYPE,
  AST_TYPE_UNION,
  AST_TYPE_YIELD,
  AST_TYPE_STRUCT,
  AST_TYPE_VARIABLE,
  AST_TYPE_POINTER,
  __AST_TYPE_KIND_END,

  // Binary operators
  __AST_BINARY_OPERATOR_START,
  AST_OP_BIN_ASSIGN,
  AST_OP_BIN_ADD,
  AST_OP_BIN_SUB,
  AST_OP_BIN_MUL,
  AST_OP_BIN_DIV,
  AST_OP_BIN_GT,
  AST_OP_BIN_LT,
  AST_OP_BIN_GE,
  AST_OP_BIN_LE,
  AST_OP_BIN_NE,
  AST_OP_BIN_EQ,
  AST_OP_MEMBER_ACCESS,
  __AST_BINARY_OPERATOR_END,

  // Unary operators
  __AST_UNARY_OPERATOR_START,
  AST_OP_UNA_SUB,
  AST_OP_UNA_ADD,
  AST_OP_POINTER_LOAD,
  AST_OP_ADDRESS_OF,
  __AST_UNARY_OPERATOR_END,

  // Applications
  __AST_CALL_OPERATION_START,
  AST_FUNCTION_CALL,
  AST_EFFECT_CALL,
  __AST_CALL_OPERATION_END,

  __AST_INTERNAL_START,
  _AST_GET_CLOSURE_HANDLER,
  _AST_GET_CLOSURE_ENVIRONMENT_BUFFER,
  _AST_SIZE_OF,
  _AST_TYPE_OF,
  _AST_BITSET,
  _AST_BITSET_SET_BIT_ON,
  _AST_BITSET_SET_BIT_OFF,
  _AST_BITSET_BINARY_UNION,
  _AST_BITSET_BINARY_INTERSECTION,
  _AST_BITSET_IS_BIT_UP,
  _AST_REALLOCATE_HEAP_BUFFER,
  _AST_ALLOCATE_HEAP_BUFFER,
  _AST_CAPTURE_VARIABLE_INTO_ENVIRONMENT,
  _AST_BORROW_VARIABLE_INTO_ENVIRONMENT,
  _AST_SETUP_CLOSURE_ENVIRONMENT_BUFFER_HEADER,
  _AST_UPDATE_CLOSURE_ENVIRONMENT_BUFFER_HEADER,
  _AST_BUILD_CLOSURE_OBJECT,
  _AST_IS_CLOSURE_OBJECT_LOCAL,
  _AST_GET_CLOSURE_ENVIRONMENT_BUFFER_SIZE,
  _AST_GET_CLOSURE_OBJECT_BITSET,
  _AST_SET_CLOSURE_OBJECT_EXTERN,
  __AST_INTERNAL_END,
  __AST_KIND_END,
};
